### ISSUE TITLE
Show the action tracking for admins

### ISSUE THREAD

**Issue by MJZwart** [MJZwart/motivation-app#588]
- [x] Add a page/tab to the admin dashboard called "Action history"
- [x] Upon loading, load all usernames + ids, all action types, the admin needs to make a choice on what to show. Show a select to filter the following:
- By user
- By action type (multiselect if possible)
- By date (range)
- [x] Click 'show' to show the action tracking with these parameters. If nothing is checked, show all. Paginated by 25 per page or so.
